name: dpul-collections
services:
  database:
    type: postgres:15
    portforward: 5434
  figgy_database:
    type: compose
    app_mount: false
    services:
      image: "ghcr.io/pulibrary/dpul-collections:figgy-fixtures"
      environment:
        POSTGRES_PASSWORD: "postgres"
      ports:
        - "5435:5432"
      # This comes from the base image ENTRYPOINT + CMD
      command: "docker-entrypoint.sh postgres"
  test_solr:
    type: lando
    build_as_root:
      - apt-get update -y && apt-get install -y zip
    healthcheck: "curl http://solr:SolrRocks@localhost:8983/solr/admin/info/health"
    run:
      - /app/bin/setup_solr.sh
    services:
      image: pulibrary/ci-solr:8.4-v1.0.0
      ports:
        - "8984:8983"
      command: bin/solr -cloud -noprompt -f -p 8983
  development_solr:
    type: lando
    build_as_root:
      - apt-get update -y && apt-get install -y zip
    healthcheck: "curl http://solr:SolrRocks@localhost:8983/solr/admin/info/health"
    run:
      - /app/bin/setup_solr.sh
    services:
      image: pulibrary/ci-solr:8.4-v1.0.0
      ports:
        - "8985:8983"
      command: bin/solr -cloud -noprompt -f -p 8983
