name: dpul-collections
services:
  database:
    type: postgres:15
    portforward: 5434
  figgy_database:
    type: postgres:15
    portforward: 5435
  test_solr:
    type: lando
    build_as_root:
      - apt-get update -y && apt-get install -y zip
    healthcheck: "curl http://solr:SolrRocks@localhost:8983/solr/admin/info/health"
    run:
      - /app/bin/setup_solr.sh
    services:
      image: quay.io/pulibrary/ci-solr:9.9-v1.0.2
      ports:
        - "8984:8983"
      command: docker-entrypoint.sh solr -cloud -noprompt -f -p 8983
      environment:
        SOLR_MODULES: 'analysis-extras,scripting'
        SOLR_CONFIG_LIB_ENABLED: true
        SOLR_SECURITY_MANAGER_ENABLED: false
  development_solr:
    type: lando
    build_as_root:
      - apt-get update -y && apt-get install -y zip
    healthcheck: "curl http://solr:SolrRocks@localhost:8983/solr/admin/info/health"
    run:
      - /app/bin/setup_solr.sh
    services:
      image: quay.io/pulibrary/ci-solr:9.9-v1.0.2
      ports:
        - "8985:8983"
      command: docker-entrypoint.sh solr -cloud -noprompt -f -p 8983
      environment:
        SOLR_MODULES: 'analysis-extras,scripting'
        SOLR_CONFIG_LIB_ENABLED: true
        SOLR_SECURITY_MANAGER_ENABLED: false
