processes:
  postgresql:
    command: "podman run -e POSTGRES_PASSWORD=postgres --rm --name dpulc_db -p 5434:5432 postgres:15"
    shutdown:
      command: "podman stop dpulc_db"
  figgy_db:
    command: "podman run -e POSTGRES_PASSWORD=postgres --rm --name dpulc_figgy_db -p 5435:5432 ghcr.io/pulibrary/dpul-collections:figgy-fixtures"
    shutdown:
      command: "podman stop dpulc_figgy_db"
  test_solr:
    command: "podman run --rm --name dpulc_test_solr -p 8984:8983 -v /mnt/$(pwd):/app pulibrary/ci-solr:8.4-v1.0.0 bin/solr -cloud -noprompt -f -p 8983"
    shutdown:
      command: "podman stop dpulc_test_solr"
  dev_solr:
    command: "podman run --rm --name dpulc_dev_solr -p 8985:8983 -v /mnt/$(pwd):/app pulibrary/ci-solr:8.4-v1.0.0 bin/solr -cloud -noprompt -f -p 8983"
    shutdown:
      command: "podman stop dpulc_dev_solr"
    #
    #
    # type: lando
    # build_as_root:
    #   - apt-get update -y && apt-get install -y zip
    # healthcheck: "curl http://solr:SolrRocks@localhost:8983/solr/admin/info/health"
    # run:
    #   - /app/bin/setup_solr.sh
    # services:
    #   image: pulibrary/ci-solr:8.4-v1.0.0
    #   ports:
    #     - "8984:8983"
    #   command: bin/solr -cloud -noprompt -f -p 8983
