[package]
name = "embedanything"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "embedanything"
crate-type = ["cdylib"]

[dependencies]
embed_anything = "0.6.4"
rustler = "0.36.2"
once_cell = "1.21.3"
tokio = { version = "1", features = ["rt-multi-thread", "macros"] }
candle-core = "0.9.1"
