defmodule DpulCollections.Classifier do
  use GenServer
  @model "hf.co/Qwen/Qwen3-Embedding-0.6B-GGUF:Q8_0"

  def start_link(_) do
    GenServer.start_link(__MODULE__, %{}, name: __MODULE__)
  end

  @impl true
  def init(_) do
    {:ok, %{client: default_client()}, {:continue, :init}}
  end

  def get_top_subjects(query) do
    case GenServer.call(__MODULE__, {:cached_embeddings}) do
      :not_loaded ->
        :timer.sleep(100)
        get_top_subjects(query)

      %{subject_embeddings: subject_embeddings, genre_embeddings: genre_embeddings} ->
        queries = [
          get_detailed_instruct(
            "Given a query return the subjects that most closely match the user need.",
            query
          ),
          get_detailed_instruct(
            "Given a query return the genres that most closely match the kind of material the user wants.",
            query
          )
        ]

        query_embedding = generate_embeddings(queries)
        subject_dot_products = Nx.dot(query_embedding[0], subject_embeddings)
        genre_dot_products = Nx.dot(query_embedding[1], genre_embeddings)

        subject_results =
          subject_dot_products
          |> Nx.to_flat_list()
          |> Enum.zip(subjects())
          |> Enum.sort(:desc)
          |> Enum.take(5)

        genre_results =
          genre_dot_products
          |> Nx.to_flat_list()
          |> Enum.zip(genres())
          |> Enum.sort(:desc)
          |> Enum.take(5)

        %{subjects: subject_results, genres: genre_results}
    end
  end

  def default_client() do
    Ollama.init("http://localhost:11439/api")
  end

  def generate_embeddings(queries, client \\ default_client()) do
    {:ok, %{"embeddings" => embeddings}} =
      Ollama.embed(client, model: "hf.co/Qwen/Qwen3-Embedding-0.6B-GGUF:f16", input: queries)

    embeddings |> Nx.tensor(type: :f16)
  end

  def handle_call(
        {:cached_embeddings},
        _from,
        state = %{subject_embeddings: subject_embeddings, genre_embeddings: genre_embeddings}
      ) do
    {:reply, state, state}
  end

  def handle_call({:cached_embeddings}, from, state) do
    {:reply, :not_loaded, state}
  end

  @impl true
  def handle_continue(:init, state = %{client: client}) do
    subjects = subjects()
               |> Enum.map(&get_detailed_instruct("This is a possible subject for a resource in a library.", &1))
    Task.async(fn -> {:subjects, generate_embeddings(subjects)} end)
    Task.async(fn -> {:genres, generate_embeddings(genres())} end)
    {:noreply, state}
  end

  def handle_info({_ref, {:subjects, subject_embeddings}}, state) do
    state =
      state
      |> Map.put(:subject_embeddings, Nx.transpose(subject_embeddings))

    {:noreply, state}
  end

  def handle_info({_ref, {:genres, genre_embeddings}}, state) do
    state =
      state
      |> Map.put(:genre_embeddings, Nx.transpose(genre_embeddings))

    {:noreply, state}
  end

  def handle_info({:DOWN, ref, _, _, reason}, state) do
    {:noreply, state}
  end

  defp get_detailed_instruct(task_description, query) do
    "Instruct: #{task_description}\nQuery:#{query}"
  end

  def genres() do
    [
      "Advertisements",
      "Bags",
      "Banners",
      "Booklets",
      "Bookmarks",
      "Books",
      "Brochures",
      "Business cards",
      "Buttons",
      "Calendars",
      "Correspondence",
      "Court decisions and opinions",
      "Electoral paraphernalia",
      "Ephemera",
      "Fans",
      "Flags",
      "Flyers",
      "Forms",
      "Games",
      "Headscarves",
      "Leaflets",
      "Magnets",
      "Manuscripts",
      "Maps",
      "Masks",
      "Montages",
      "News clippings",
      "Newsletters",
      "Newspapers",
      "Paintings",
      "Pamphlets",
      "Pedagogical materials",
      "Pennants",
      "Periodical",
      "Photographs",
      "Picket signs",
      "Postcards",
      "Posters",
      "Reports",
      "Serials",
      "Series",
      "Stickers",
      "T-shirts",
      "Video recordings"
    ]
  end

  def subjects() do
    [
      "Politics and government",
      "Arts and culture",
      "Labor",
      "Labor economics",
      "Elections",
      "Socioeconomic conditions and development",
      "Arts",
      "Human and civil rights",
      "Economics",
      "Gender and sexuality",
      "Politics",
      "Education",
      "Health",
      "Protest movements",
      "Motion pictures",
      "Environment and ecology",
      "Children and youth",
      "Political campaigns",
      "Advertising",
      "Minorities, ethnic and racial groups",
      "History",
      "Propaganda",
      "Labor unions",
      "Local government",
      "Agrarian and rural issues",
      "Artists",
      "Political parties",
      "Economic and social development",
      "Social movements",
      "Politics and culture",
      "Religion",
      "War",
      "Museum exhibits",
      "Culture",
      "Tourism",
      "Kommunisticheskai︠a︡ partii︠a︡ Sovetskogo Soi︠u︡za",
      "Human rights",
      "Social conditions",
      "Presidents",
      "Photography",
      "Collective memory",
      "Local history",
      "Universities and colleges",
      "Women's rights",
      "Political participation",
      "Armed Forces",
      "Festivals",
      "Economic conditions",
      "Women",
      "Caricatures and cartoons",
      "Performing arts",
      "Indigenous peoples",
      "Health education",
      "Children",
      "Labor laws and legislation",
      "Social justice",
      "Women--Crimes against",
      "Lenin, Vladimir Ilʹich, 1870-1924",
      "Revolutionaries",
      "Students--Political activity",
      "Urban issues",
      "Socialism",
      "Government policy",
      "Science and Technology",
      "Labor unions--Political activity",
      "Democracy",
      "Human rights advocacy",
      "Women--Political activity",
      "Advertising--Tourism",
      "Arts--Political aspects",
      "Pensions",
      "Economic development",
      "Universities and students",
      "Youth",
      "Communism",
      "Revolutions",
      "Social problems",
      "Sports",
      "Public health",
      "World War, 1939-1945",
      "Working class",
      "Student unions",
      "Community development",
      "Mass media",
      "Laws",
      "Wages",
      "Literature",
      "Environmental protection",
      "Popular culture",
      "Music",
      "Employee rights",
      "Employment",
      "Education--Study and teaching",
      "Voting",
      "Books and reading",
      "Foreign relations",
      "International relations",
      "Education--Political aspects",
      "Disappeared persons",
      "Strikes and lockouts",
      "Agriculture",
      "Political violence",
      "Unemployed",
      "Discrimination",
      "Medical care",
      "Feminism",
      "Recreation",
      "Economic policy",
      "Mines and mineral resources",
      "Work environment",
      "Social policy--Citizen participation",
      "Political prisoners",
      "Finance",
      "Community organization",
      "Constitutions",
      "Social policy",
      "Sociology",
      "Children's rights",
      "Diseases",
      "Folklore",
      "Schools",
      "Youth--Political activity",
      "Celebrities",
      "Public administration",
      "Holidays",
      "Industries",
      "Catholic Church",
      "Family",
      "State-sponsored terrorism",
      "Substance abuse",
      "Gender",
      "Environmental education",
      "Self-determination, National",
      "Blacks",
      "Child welfare",
      "AIDS (Disease)",
      "Islam",
      "Christians",
      "Peace movements",
      "Autonomy and independence movements",
      "Citizen participation",
      "Teachers' unions",
      "Education and state",
      "Retirees",
      "Government accountability",
      "Environment",
      "Abortion",
      "Poverty",
      "HIV infections",
      "Reproductive rights",
      "Agricultural development projects",
      "Economics--Political aspects",
      "Science and technology",
      "Museums",
      "Water use",
      "Public safety",
      "Nutrition",
      "Political corruption",
      "Women--Legal status, laws, etc.",
      "Economic assistance",
      "Conservation of natural resources",
      "Indigenous peoples--Civil rights",
      "Sustainable development",
      "Imperialism",
      "Civil rights",
      "Forests and forestry",
      "Religion and politics",
      "Women--Employment",
      "Tourist maps",
      "Police brutality",
      "Agriculture--Handbooks, manuals, etc.",
      "Child labor",
      "Societies and clubs",
      "Violence",
      "Business",
      "Human rights--Law and legislation",
      "Indigenous peoples--Legal status, laws, etc.",
      "Rural development projects",
      "Water resources",
      "Commerce",
      "Domestic violence",
      "Family violence",
      "Urban transportation",
      "Economic development projects",
      "Banks and banking",
      "Transgender people",
      "Libraries",
      "Agricultural workers",
      "Information technology",
      "Art fairs",
      "LGBTQ+ people",
      "Child care",
      "Sexual health",
      "Mental health",
      "Housing",
      "Education, Higher",
      "Freedom of expression",
      "Mass media--Political aspects",
      "Nationalism",
      "International cooperation",
      "Peace agreements",
      "Health policy",
      "Women--Government policy",
      "Sexual abuse victims",
      "Human rights--Government policy",
      "Natural resources",
      "Hinduism",
      "Reproductive health",
      "Nature conservation",
      "Migrant Labor",
      "Minorities",
      "Health facilities",
      "Wildlife conservation",
      "Natural disasters",
      "Judicial system",
      "Community development--Environmental aspects",
      "Religious education",
      "Sex discrimination against women",
      "Cities",
      "Ecotourism",
      "Rural conditions",
      "Biography",
      "Occupational training",
      "Gay rights",
      "Transportation",
      "Women's health",
      "Educational system",
      "Women--Health and hygiene",
      "Economic policy--Social aspects",
      "Rural and village development",
      "Civil society",
      "Documentary films",
      "Sanitation",
      "Sustainable agriculture",
      "Environmental policy",
      "Prisons",
      "Health services accessibility",
      "Racism",
      "Biodiversity",
      "Fiscal policy",
      "Food supply",
      "Agriculture--Economic aspects",
      "Hindu nationalism",
      "National parks and reserves",
      "Food industry",
      "Lesbians",
      "Rites and ceremonies",
      "Popular education",
      "Gays",
      "Women--Education",
      "Civil rights--Government policy",
      "Gastronomy",
      "Guidebooks",
      "Industrialization",
      "Language and languages",
      "Trade associations",
      "Animal welfare",
      "Courts",
      "Agricultural industries",
      "Bible",
      "Consumer protection",
      "Educational law and legislation",
      "Land reform",
      "Local government --Economic aspects",
      "Hotels and motels",
      "Intellectuals",
      "Pollution",
      "Children--Crimes against",
      "Contraception",
      "Public health--Citizenship participation",
      "Tourism and gastronomy",
      "Child sexual abuse",
      "Infrastructure (Economics)",
      "Police",
      "Foreign and trade relations",
      "Indigenous women",
      "Brezhnev, Leonid Ilʹich, 1906-1982",
      "Children--Government policy",
      "Climate change",
      "Technical assistance",
      "Ecology",
      "Oil industries",
      "Energy policy",
      "Human trafficking",
      "Sex discrimination",
      "City planning",
      "Ethnic groups",
      "Education, Primary",
      "Hydrocarbons",
      "International agencies",
      "Older people",
      "Science education",
      "Protestant churches",
      "Families",
      "Folk art",
      "Agriculture and state",
      "Children--Health and hygiene",
      "Capitalism",
      "Islam and politics",
      "Demography",
      "Massacres",
      "Agricultural technology",
      "Agriculture and politics",
      "People with disabilities",
      "Environmentalism",
      "Recycling (Waste, etc.); Waste disposal",
      "Torture",
      "Vocational education",
      "Art--Study and teaching",
      "Marketing",
      "Archives",
      "Architecture",
      "Migration",
      "Debts, External",
      "Literacy",
      "Ethnic relations",
      "Child nutrition",
      "Administrative regulations",
      "Gay culture",
      "Monuments",
      "Energy Technology",
      "Immigrants--Civil rights",
      "Indigenous art",
      "Spiritualism",
      "Cooperative societies",
      "Crime",
      "Decentralization in government",
      "Evangelicalism",
      "Women in development",
      "Peace negotiations",
      "Immigrants",
      "Animal rights",
      "Children--Legal status, laws, etc.",
      "International business enterprises",
      "Women in art",
      "Child abuse",
      "Iran",
      "National security",
      "Economic policy--citizen participation",
      "Men",
      "Family planning",
      "Crime prevention",
      "Petroleum industry and trade",
      "Religious art",
      "Traditional farming",
      "Small business",
      "Consumer protection--Economic aspects",
      "Youth and violence",
      "Privatization",
      "Youth--Drug use",
      "Agricultural laws and legislation",
      "Globalization",
      "Immunization",
      "Urban population",
      "Drug policy",
      "Emblems, National",
      "Income distribution",
      "Liberation theology",
      "Archaeology",
      "Multicultural education",
      "Real estate business",
      "Youth--Sexual behavior",
      "NGOs",
      "Adult education",
      "Management",
      "Minorities--Legal status, laws, etc.",
      "Renewable energy resources",
      "Waste disposal",
      "Ethnic art",
      "Latin America--Relations--United States; United States--Relations--Latin America",
      "Retirement",
      "20th century",
      "Minorities--Political activity",
      "Women--Identity",
      "Refugees--Civil rights",
      "Water--Health aspects",
      "Youth--Civil rights",
      "Older people--Civil rights",
      "Public safety--Social aspects",
      "Forced migration",
      "Freedom of the press",
      "Buddhism",
      "Land use, urban",
      "Policy analysis",
      "Tourism--Economic aspects",
      "Early childhood education",
      "Energy conservation",
      "Environmental law",
      "Masculinity",
      "Public works",
      "Qurʼan",
      "Sex instruction",
      "Stalin, Joseph, 1878-1953",
      "Truth commissions",
      "Industries and industrial policy",
      "Sexual minorities",
      "Gays--Legal status, laws, etc.",
      "Power resources--Environmental aspects",
      "Tourism and art",
      "Bharatiya Janata Party (BJP)",
      "Environmental health",
      "Investments, Foreign",
      "Separatist movements",
      "Youth--Health and hygiene",
      "Church and state",
      "Drug traffic",
      "Natural gas",
      "Power resources",
      "Health--Environmental aspects",
      "People with disabilities--Civil rights",
      "Minorities--Civil rights",
      "Organic farming",
      "Energy",
      "Youth employment",
      "Prostitution",
      "Terrorism",
      "Urban policy--Environmental aspects",
      "Religious architecture",
      "Secularism",
      "Women household employees",
      "Archaeological sites",
      "Building",
      "Dalits",
      "Micro finance",
      "Mineral industries--Environmental aspects",
      "Traditional medicine",
      "Women--Sexual behavior",
      "Communalism",
      "Education, Rural",
      "Guerrillas",
      "Latin America--Relations--United States",
      "Rashtriya Swayam Sevak Sangh (RSS)",
      "Atheism",
      "Teaching--Aids and devices",
      "Agricultural Research Institute",
      "Agricultural exhibitions",
      "Research institutes",
      "Engineering",
      "Land tenure",
      "Missing children",
      "Education, Bilingual",
      "Green technology",
      "Minorities--Education",
      "Urbanization",
      "Disaster planning and relief",
      "Housing policy",
      "Marine resources",
      "Poor children",
      "Youth--Attitudes",
      "Ecumenical movement",
      "Sex",
      "Tourist camps, hostels, etc.",
      "Urban violence",
      "Birth control",
      "Lesbian culture",
      "Philately",
      "Labor and globalization",
      "Abandoned children",
      "Biotechnology",
      "Minorities--Politics and government",
      "Missionaries",
      "Pan-Americanism",
      "Teenagers",
      "Caste",
      "Rain forests",
      "Boycotts",
      "Consumer behavior",
      "Economics--Research",
      "Men--Sexual behavior",
      "Temples",
      "Tourism--Social aspects",
      "Marriage",
      "Pests",
      "Adoption",
      "Ethnicity",
      "Ethnicity--Political aspects",
      "Indian National Congress Party",
      "Youth--Alcohol use",
      "Astronautics",
      "Education, Secondary",
      "Military Technology",
      "Poor--Education",
      "Slavery",
      "Flowers",
      "Juvenile delinquency",
      "Labor market",
      "Macroeconomics",
      "Muḥammad, Prophet, -632",
      "Urban renewal",
      "Viśva Hindū Parishad",
      "Communist Party of India (Marxist) – CPI(M)",
      "Fish trade--Environmental aspects",
      "Non formal education",
      "Physicians",
      "United States--Relations--Latin America",
      "Afro-Brazilian cults",
      "Animal culture",
      "Fish trade",
      "Jehovah's Witnesses",
      "Press coverage",
      "Students",
      "Agriculture--International cooperation",
      "Cattle trade",
      "Medical technology",
      "South Asian Association of Regional Cooperation (SAARC)",
      "Gay couples",
      "Genetically modified foods",
      "Homosexuality--Government policy",
      "Judaism",
      "Pre-Columbian art",
      "Alternative medicine",
      "Asians",
      "Drugs--Therapeutic use",
      "Forced labor",
      "Fraud",
      "Indians--Religion",
      "Transgenic plants",
      "Affirmative action",
      "Fisheries",
      "Forestry",
      "Geology",
      "Minorities--Population",
      "Same-sex marriage",
      "Communist Party of India - Maoist – CPI-Maoist",
      "HIV-positive persons",
      "Hadith",
      "Paramilitary forces",
      "Shīrāz",
      "Agriculture, Cooperative",
      "Border security",
      "Fārs",
      "Industrial accidents",
      "Nuclear technology",
      "Arabs",
      "Coffee industry",
      "Sikhism",
      "Afro-Caribbean cults",
      "Famines",
      "Paramilitaries",
      "Collectivization of agriculture",
      "Discrimination in medical care",
      "Divorce",
      "European Union countries",
      "Fars",
      "Freemasonry",
      "Independent churches",
      "Mass media--Economic aspects",
      "Urban-rural migration",
      "Conversion",
      "Informal sector (Economics)",
      "Pilgrims and pilgrimages",
      "Sufism",
      "Ahmadiyya",
      "Anarchism",
      "Citizenship & Basic Rights / Cidadania & Direitos Básicos",
      "Numismatics",
      "Postal service",
      "Squatter settlements",
      "Street protest & Strike  Protesto de rua & Greve",
      "Armies",
      "Dropouts",
      "Episcopal Church",
      "Europeans",
      "Jainism",
      "Mosques",
      "Reza Shah Pahlavi Shah of Iran 1878-1944",
      "Saints",
      "Banana trade",
      "Church of England",
      "Correspondence",
      "Europeans--Politics and government",
      "Ismailites",
      "Law and legislation",
      "Majlis-i Shūrā-yi Millī",
      "Political activity",
      "Public contracts",
      "Shiraz",
      "Taxation",
      "1914-1921",
      "20t century",
      "20th Century",
      "Arya-Samaj",
      "Auctions",
      "Āyram, Maḥmūd Khān",
      "Baghdad",
      "Bayān-i ḥaqīqat",
      "Bharatiya Jan Sangh",
      "Bread",
      "Būshihr",
      "Conditional sales",
      "Davākhānah-i ʻUmūmī-i Naqīb al-Mamālik",
      "Doctrines",
      "Feria de Turismo Regional (FETUR) ",
      "Firearms",
      "Firqah-i Dimūkrāt-i Īrān Kumītah-i Shīrāz",
      "Firqah-ʼi Dimūkrāt-i Fārs",
      "Gangs",
      "Germany",
      "Gun control",
      "Hayʼat-i Muttaḥidīn-i Āz̲arbāyjān va Mutaḥiṣṣinīn",
      "Indo-Aryans",
      "Iraq",
      "Islamic fundamentalism",
      "Iṣfahānī, Ḥājjī ʻAbbās [Browse]",
      "JamʻĪyat-i Aḥrār-i Fārs",
      "Jangalī movement",
      "Khazʻal Khān Amir of Muḥammarah",
      "Khūzistān",
      "Kumīsyūn-i Mukhtaliṭ-i Nahz̤at-i Millī",
      "Kumītah-i Ayālatī-i Ukhuvvat-i Dīmūkrāt-i Fārs",
      "Kurds",
      "Lārī",
      "Maʻārif",
      "Mestizos",
      "Naji, Mohammad Amir",
      "Plague",
      "Poetry",
      "Politics and goverment",
      "Politics and government - courts",
      "Politics and government -- courts",
      "Prices",
      "Protest movement",
      "Rawnaq al-Dawlah, Fatḥ ʻAlī",
      "Real property",
      "Refuse and refuse disposal",
      "Refuse desposal",
      "Relations",
      "Reza Shah Pahlavi",
      "Social life and customs",
      "Sources",
      "Tibetan government in exile",
      "Tribes",
      "Ulama",
      "Wahhābīyah",
      "democr",
      "local elections",
      "local governemnt",
      "mass",
      "motion",
      "photography",
      "politicl campaigns",
      "teachers",
      "univsersities and colleges",
      "ʻAbd al-Ḥusayn al-Najafī"
    ]
  end
end
