on:
  workflow_dispatch:
  schedule:
    - cron: "5 * * * *"  # every hour
  pull_request:
    branches:
      - main

jobs:
  clean:
    runs-on: ubuntu-latest
    name: Delete old images
    steps:
      - uses: snok/container-retention-policy@v3.0.0
        with:
          account: pulibrary
          token: ${{ secrets.GITHUB_TOKEN }}
          image-names: "dpul-collections"
          image-tags: "!main pr-* sha-*"
          cut-off: 2w
          keep-n-most-recent: 10
          dry-run: false
